name: Round-robin assign reviewer
on:
    pull_request:
        types:
            - review_requested
jobs:
    assign-reviewer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/github-script@v7
              env:
                  SHA: '${{env.parentSHA}}'
              with:
                  script: |
                      const reviewer = context.requested_reviewer;

                      console.log(reviewer)
