name: Security

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    if: "false"
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
    - uses: actions/checkout@v4
    - name: Dependencies audit
      run: yarn audit --groups dependencies --level high
